--[[
    =====================================================================
    ENCRYPTION.LUA - FiveM Edition (Enum Version)
    Taken from FXEvents and ported to Lua by manups4e
    =====================================================================
]]

Encryption = {}

-- Recovery of the SHA module via Getter
local crypto = GetShaObject()
local chacha = GetChaCha20()
local MAGIC_MARKER = "FX!"

-- ENUM for Algorithms
Encryption.Algos = {
    -- Classic
    CHACHA20  = "chacha20",  -- for speed at max
    XCHACHA20 = "xchacha20", -- for speed with maximum performances (best fivem approach)
    MD5       = "md5",
    SHA1      = "sha1",

    -- SHA-2 (Standard)
    SHA224    = "sha224",
    SHA256    = "sha256",
    SHA384    = "sha384",
    SHA512    = "sha512",

    -- SHA-3 (Modern & Ultra-Secure)
    SHA3_256  = "sha3_256",
    SHA3_512  = "sha3_512",

    -- BLAKE (High Performance)
    BLAKE2B   = "blake2b",
    BLAKE3    = "blake3",
}
math.randomseed(GetGameTimer())

-------------------------------------------------------------------------------
-- 1. INTERNAL HELPERS
-------------------------------------------------------------------------------

--- Generates a hash byte table using the specified algorithm
function Encryption.GenerateHash(input, algo)
    -- Use the enum value or default to SHA256
    algo = algo or Encryption.Algos.SHA256

    if not crypto or not crypto[algo] then
        print("^1[Encryption] Error: Algorithm '" .. tostring(algo) .. "' not supported!^7")
        return nil
    end

    local binaryString = crypto[algo](input)
    local byteTable = {}
    for i = 1, #binaryString do
        byteTable[i] = string.byte(binaryString, i)
    end

    return byteTable
end

-------------------------------------------------------------------------------
-- 2. CORE OBJECT ENCRYPTION
-------------------------------------------------------------------------------

function Encryption.GenerateKeyPair()
    -- Instantiate the Curve25519 object
    local curve = Curve25519.Create()

    -- GetPublicKey() internally generates a random private key if not set
    local publicKey = curve:GetPublicKey()

    -- Access the internal private key generated by the class
    return {
        privateKey = curve._privateKey,
        publicKey = publicKey
    }
end

function Encryption.GetSharedSecret(privateKey, remotePublicKey)
    -- Validate input types to prevent math errors in the inner core
    assert(type(privateKey) == "table", "Sigrdrífa: privateKey must be a byte table")
    assert(type(remotePublicKey) == "table", "Sigrdrífa: remotePublicKey must be a byte table")

    local curve = Curve25519.Create()
    curve:FromPrivateKey(privateKey)

    return curve:GetSharedSecret(remotePublicKey)
end

--- Encrypts any Lua object
--- Encrypts any Lua object into a byte table
-- Supports tables, strings, numbers, and booleans.
-- @param obj any: The data to protect
-- @param key string/table: The passphrase or shared secret
-- @param algo string: (Optional) Encryption/Hash algorithm
-- @return table: Encrypted byte array
function Encryption.EncryptObject(obj, key, algo)
    if obj == nil or key == nil then return nil end
    if #key < 3 then return nil, "KEY_TOO_SHORT" end

    -- Default to SHA256 if no algorithm is provided
    algo = algo or Encryption.Algos.SHA256
    local jsonStr = json.encode(obj)

    ---------------------------------------------------------------------------
    -- CHACHA20 / XCHACHA20 LOGIC
    ---------------------------------------------------------------------------
    if algo == Encryption.Algos.CHACHA20 or algo == Encryption.Algos.XCHACHA20 then
        -- ChaCha20 requires a strict 32-byte key.
        -- If a string is provided, we hash it to SHA256 (32 bytes) to ensure compatibility.
        local rawKey = type(key) == "string" and
        Encryption.BytesToBinaryString(Encryption.GenerateHash(key, Encryption.Algos.SHA256)) or key

        -- Generate a unique random Nonce (12 bytes for ChaCha20, 24 bytes for XChaCha20)
        -- Using a unique nonce per message is critical to prevent stream cipher reuse attacks.
        local nonceSize = (algo == Encryption.Algos.XCHACHA20) and 24 or 12
        local nonce = util.getRandomString(nonceSize)

        -- Perform encryption (returns a binary string)
        local encrypted
        if algo == Encryption.Algos.XCHACHA20 then
            encrypted = chacha.xchacha20_encrypt(rawKey, 0, nonce, jsonStr)
        else
            encrypted = chacha.chacha20_encrypt(rawKey, 0, nonce, jsonStr)
        end

        -- Build final payload: MAGIC_MARKER + ALGO + SEPARATOR + NONCE + CIPHERTEXT
        -- This allows the decryptor to know exactly which settings were used.
        local finalStr = MAGIC_MARKER .. algo .. "|" .. nonce .. encrypted

        -- Convert the binary string back to a byte table for consistency with FiveM exports
        return { string.byte(finalStr, 1, #finalStr) }
    end

    ---------------------------------------------------------------------------
    -- CLASSIC XOR LOGIC (Fallback/Standard Hashes)
    ---------------------------------------------------------------------------
    local payload = MAGIC_MARKER .. algo .. "|" .. jsonStr
    local dataBytes = { string.byte(payload, 1, #payload) }

    -- Generate the keystream bytes based on the provided key and hash algorithm
    local keyBytes = type(key) == "string" and Encryption.GenerateHash(key, algo) or key

    local output = {}
    for i = 1, #dataBytes do
        -- Apply circular XOR against the keystream
        local keyByte = keyBytes[((i - 1) % #keyBytes) + 1]
        output[i] = dataBytes[i] ~ keyByte
    end

    return output
end

--- Decrypts a byte array and validates its integrity
-- @param encryptedData table: The array of encrypted bytes
-- @param key string: The decryption key/passphrase
-- @param forceAlgo string: (Optional) Specifically force a certain algorithm
-- @return any: The original decoded object, or nil if decryption fails
function Encryption.DecryptObject(encryptedData, key, forceAlgo)
    if not encryptedData or #encryptedData == 0 then return nil, "EMPTY_DATA" end
    if key == nil or #key < 3 then return nil, "INVALID_KEY" end

    -- Determine which algorithms to attempt (ChaCha variants prioritized for speed/security)
    local algosToTry = forceAlgo and { forceAlgo } or {
        Encryption.Algos.XCHACHA20,
        Encryption.Algos.CHACHA20,
        Encryption.Algos.BLAKE3,
        Encryption.Algos.SHA256,
        Encryption.Algos.SHA512,
        Encryption.Algos.MD5,
        Encryption.Algos.SHA1,
        Encryption.Algos.SHA224,
        Encryption.Algos.SHA384,
        Encryption.Algos.SHA3_256,
        Encryption.Algos.SHA3_512,
        Encryption.Algos.BLAKE2B
    }

    for _, algo in ipairs(algosToTry) do
        local decryptedStr = ""

        if algo == Encryption.Algos.XCHACHA20 or algo == Encryption.Algos.CHACHA20 then
            -------------------------------------------------------------------
            -- CHACHA20 DECRYPTION PROCESS
            -------------------------------------------------------------------
            -- Convert byte table back to a binary string for processing
            local fullBinary = Encryption.BytesToBinaryString(encryptedData)

            -- Prepare the 32-byte key (hashed if necessary)
            local rawKey = type(key) == "string" and
            Encryption.BytesToBinaryString(Encryption.GenerateHash(key, Encryption.Algos.SHA256)) or key

            -- Define expected header to locate the Nonce and Ciphertext start positions
            local expectedHeader = MAGIC_MARKER .. algo .. "|"
            local nonceSize = (algo == Encryption.Algos.XCHACHA20) and 24 or 12

            -- Extract Nonce and Ciphertext from the raw payload
            local startOffset = #expectedHeader + 1
            local nonce = fullBinary:sub(startOffset, startOffset + nonceSize - 1)
            local ciphertext = fullBinary:sub(startOffset + nonceSize)

            -- Proceed if the nonce length is valid
            if #nonce == nonceSize then
                if algo == Encryption.Algos.XCHACHA20 then
                    decryptedStr = chacha.xchacha20_decrypt(rawKey, 0, nonce, ciphertext)
                else
                    decryptedStr = chacha.chacha20_decrypt(rawKey, 0, nonce, ciphertext)
                end
            end
        else
            -------------------------------------------------------------------
            -- XOR DECRYPTION PROCESS
            -------------------------------------------------------------------
            local keyBytes = type(key) == "string" and Encryption.GenerateHash(key, algo) or key
            local chars = {}
            for i = 1, #encryptedData do
                local keyByte = keyBytes[((i - 1) % #keyBytes) + 1]
                chars[i] = string.char(encryptedData[i] ~ keyByte)
            end
            decryptedStr = table.concat(chars)
        end

        -----------------------------------------------------------------------
        -- FINAL VALIDATION & JSON DECODING
        -----------------------------------------------------------------------
        -- Check if the decrypted string starts with the Magic Marker (Integrity Check)
        if decryptedStr:sub(1, #MAGIC_MARKER) == MAGIC_MARKER or (algo:find("chacha") and decryptedStr ~= "") then
            local jsonStr = decryptedStr

            -- If the marker is embedded in the string (XOR style), extract the JSON part
            if decryptedStr:sub(1, #MAGIC_MARKER) == MAGIC_MARKER then
                local headerEnd = decryptedStr:find("|")
                if headerEnd then
                    jsonStr = decryptedStr:sub(headerEnd + 1)
                end
            end

            -- Attempt to decode the JSON payload back into its original Lua type
            local success, result = pcall(json.decode, jsonStr)
            if success then return result, nil end
        end

        ::next_algo::
    end

    return nil, "INVALID_KEY_OR_ALGO"
end

-------------------------------------------------------------------------------
-- 3. UTILITIES
-------------------------------------------------------------------------------

function Encryption.ToHex(bytes, separator)
    separator = separator or ""
    local hex = {}
    for i = 1, #bytes do table.insert(hex, string.format("%02X", bytes[i])) end
    return table.concat(hex, separator)
end

function Encryption.ToBase64(bytes)
    -- We use our binary string helper before passing to the library's base64
    local binStr = Encryption.BytesToBinaryString(bytes)
    return crypto.bin_to_base64(binStr)
end

--- Converts a byte table to a binary string
function Encryption.BytesToBinaryString(bytes)
    local result = {}
    for i = 1, #bytes do
        result[i] = string.char(bytes[i]) -- Converte il byte puro senza modifiche
    end
    return table.concat(result)
end

--- For printing purposes
function Encryption.ToEscapedString(bytes)
    local result = {}
    for i = 1, #bytes do
        local b = bytes[i]
        if b >= 32 and b <= 126 then
            table.insert(result, string.char(b))
        else
            table.insert(result, "\\" .. b)
        end
    end
    return table.concat(result)
end
